<h2 class="newsletter-title">
    <?= __('Junte-se à nossa comunidade e compartilhe <br> experiências inspiradoras!') ?>
</h2>
<p class="newsletter-subtitle">
    <?= __('Inscreva-se na nossa newsletter para receber atualizações exclusivas, ofertas especiais e dicas inspiradoras diretamente na sua caixa de entrada. <br>Junte-se a nós e faça parte de uma comunidade apaixonada por moda e estilo!') ?>
</p>